Homepage: 
    path: /
    controller: App\Controller\HomepageController::index

article_show:
    path: /{id}
    controller: App\Controller\ArticleController::index
    requirements:
        id: '\d+'

article_add:
    path: /add
    controller: App\Controller\ArticleController::edit

article_edit:
    path: /edit/{id}
    controller: App\Controller\ArticleController::edit
    requirements:
        id: '\d+'

article_delete:
    path: /delete/{id}
    controller: App\Controller\ArticleController::delete
    requirements:
        id: '\d+'

